name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Grant execute permission
      run: chmod +x gradlew

    - name: Assemble Debug
      run: ./gradlew :sample:todo:android:assembleDebug --stacktrace

    - name: Unit Test
      run: ./gradlew :sample:todo:android:test --stacktrace

    - name: Upload Debug‑APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: sample/todo/android/build/outputs/apk/debug/*.apk
